/* Auto-generated by scripts/export-abis.mjs. Do not edit manually. */
/* eslint-disable */
import type { Abi } from "viem";
import abiManifestJson from "./manifest.json";

import AgriCampaignRegistryJson from "./contracts/AgriCampaignRegistry.abi.json";
import AgriShareTokenJson from "./contracts/AgriShareToken.abi.json";
import BatchMerkleAnchorJson from "./contracts/BatchMerkleAnchor.abi.json";
import BridgeModuleJson from "./contracts/BridgeModule.abi.json";
import CampaignFactoryJson from "./contracts/CampaignFactory.abi.json";
import CampaignTemplateJson from "./contracts/CampaignTemplate.abi.json";
import CampaignTreasuryJson from "./contracts/CampaignTreasury.abi.json";
import ChainlinkAdapterJson from "./contracts/ChainlinkAdapter.abi.json";
import ClonesLibJson from "./contracts/ClonesLib.abi.json";
import ComplianceModuleV1Json from "./contracts/ComplianceModuleV1.abi.json";
import CustodyOracleJson from "./contracts/CustodyOracle.abi.json";
import DeliveryModuleJson from "./contracts/DeliveryModule.abi.json";
import DisasterEvidenceOracleJson from "./contracts/DisasterEvidenceOracle.abi.json";
import DisasterModuleJson from "./contracts/DisasterModule.abi.json";
import DocumentRegistryJson from "./contracts/DocumentRegistry.abi.json";
import ECDSAJson from "./contracts/ECDSA.abi.json";
import EIP712Json from "./contracts/EIP712.abi.json";
import EmergencyPauseJson from "./contracts/EmergencyPause.abi.json";
import EUProfileEUDRComplianceJson from "./contracts/EUProfileEUDRCompliance.abi.json";
import ForcedTransferControllerJson from "./contracts/ForcedTransferController.abi.json";
import FreezeManagerJson from "./contracts/FreezeManager.abi.json";
import FundingManagerJson from "./contracts/FundingManager.abi.json";
import HarvestOracleJson from "./contracts/HarvestOracle.abi.json";
import IdentityAttestationJson from "./contracts/IdentityAttestation.abi.json";
import InsurancePoolJson from "./contracts/InsurancePool.abi.json";
import MarketplaceModuleJson from "./contracts/MarketplaceModule.abi.json";
import OracleBaseEIP712Json from "./contracts/OracleBaseEIP712.abi.json";
import PackedUintJson from "./contracts/PackedUint.abi.json";
import ReentrancyGuardJson from "./contracts/ReentrancyGuard.abi.json";
import RoleManagerJson from "./contracts/RoleManager.abi.json";
import SafeERC20Json from "./contracts/SafeERC20.abi.json";
import SalesProceedsOracleJson from "./contracts/SalesProceedsOracle.abi.json";
import SettlementQueueJson from "./contracts/SettlementQueue.abi.json";
import SnapshotModuleJson from "./contracts/SnapshotModule.abi.json";
import TraceabilityRegistryJson from "./contracts/TraceabilityRegistry.abi.json";
import TwoStepAdminJson from "./contracts/TwoStepAdmin.abi.json";
import UAgriErrorsJson from "./contracts/UAgriErrors.abi.json";
import YieldAccumulatorJson from "./contracts/YieldAccumulator.abi.json";
import IAggregatorV3Json from "./interfaces/IAggregatorV3.abi.json";
import IAgriBridgeV1Json from "./interfaces/IAgriBridgeV1.abi.json";
import IAgriCampaignRegistryV1Json from "./interfaces/IAgriCampaignRegistryV1.abi.json";
import IAgriComplianceV1Json from "./interfaces/IAgriComplianceV1.abi.json";
import IAgriCustodyV1Json from "./interfaces/IAgriCustodyV1.abi.json";
import IAgriDeliveryV1Json from "./interfaces/IAgriDeliveryV1.abi.json";
import IAgriDisasterAdminV1Json from "./interfaces/IAgriDisasterAdminV1.abi.json";
import IAgriDisasterV1Json from "./interfaces/IAgriDisasterV1.abi.json";
import IAgriDistributionHooksV1Json from "./interfaces/IAgriDistributionHooksV1.abi.json";
import IAgriDistributionV1Json from "./interfaces/IAgriDistributionV1.abi.json";
import IAgriDocumentRegistryV1Json from "./interfaces/IAgriDocumentRegistryV1.abi.json";
import IAgriForcedTransferV1Json from "./interfaces/IAgriForcedTransferV1.abi.json";
import IAgriFreezeV1Json from "./interfaces/IAgriFreezeV1.abi.json";
import IAgriIdentityAttestationV1Json from "./interfaces/IAgriIdentityAttestationV1.abi.json";
import IAgriInsuranceV1Json from "./interfaces/IAgriInsuranceV1.abi.json";
import IAgriMarketplaceV1Json from "./interfaces/IAgriMarketplaceV1.abi.json";
import IAgriModulesV1Json from "./interfaces/IAgriModulesV1.abi.json";
import IAgriOracleBaseV1Json from "./interfaces/IAgriOracleBaseV1.abi.json";
import IAgriOracleSubmitV1Json from "./interfaces/IAgriOracleSubmitV1.abi.json";
import IAgriShareOpsJson from "./interfaces/IAgriShareOps.abi.json";
import IAgriShareTokenSnapshotViewsJson from "./interfaces/IAgriShareTokenSnapshotViews.abi.json";
import IAgriTraceV1Json from "./interfaces/IAgriTraceV1.abi.json";
import IAgriTreasuryV1Json from "./interfaces/IAgriTreasuryV1.abi.json";
import IERC1271_IdentityAttestationJson from "./interfaces/IERC1271__IdentityAttestation.abi.json";
import IERC1271_OracleBaseEIP712Json from "./interfaces/IERC1271__OracleBaseEIP712.abi.json";
import IERC1271_YieldAccumulatorJson from "./interfaces/IERC1271__YieldAccumulator.abi.json";
import IFundingManagerQueueV1Json from "./interfaces/IFundingManagerQueueV1.abi.json";
import ISettlementQueueV1Json from "./interfaces/ISettlementQueueV1.abi.json";
import IShareTokenViewsJson from "./interfaces/IShareTokenViews.abi.json";
import ISnapshotModuleLikeJson from "./interfaces/ISnapshotModuleLike.abi.json";
import IERC1271Json from "./standards/IERC1271.abi.json";
import IERC165Json from "./standards/IERC165.abi.json";
import IERC20Json from "./standards/IERC20.abi.json";
import IERC20DecimalsJson from "./standards/IERC20Decimals.abi.json";
import IERC7943FungibleJson from "./standards/IERC7943Fungible.abi.json";

export const abiByName: Record<string, Abi> = {
  "AgriCampaignRegistry": AgriCampaignRegistryJson as unknown as Abi,
  "AgriShareToken": AgriShareTokenJson as unknown as Abi,
  "BatchMerkleAnchor": BatchMerkleAnchorJson as unknown as Abi,
  "BridgeModule": BridgeModuleJson as unknown as Abi,
  "CampaignFactory": CampaignFactoryJson as unknown as Abi,
  "CampaignTemplate": CampaignTemplateJson as unknown as Abi,
  "CampaignTreasury": CampaignTreasuryJson as unknown as Abi,
  "ChainlinkAdapter": ChainlinkAdapterJson as unknown as Abi,
  "ClonesLib": ClonesLibJson as unknown as Abi,
  "ComplianceModuleV1": ComplianceModuleV1Json as unknown as Abi,
  "CustodyOracle": CustodyOracleJson as unknown as Abi,
  "DeliveryModule": DeliveryModuleJson as unknown as Abi,
  "DisasterEvidenceOracle": DisasterEvidenceOracleJson as unknown as Abi,
  "DisasterModule": DisasterModuleJson as unknown as Abi,
  "DocumentRegistry": DocumentRegistryJson as unknown as Abi,
  "ECDSA": ECDSAJson as unknown as Abi,
  "EIP712": EIP712Json as unknown as Abi,
  "EmergencyPause": EmergencyPauseJson as unknown as Abi,
  "EUProfileEUDRCompliance": EUProfileEUDRComplianceJson as unknown as Abi,
  "ForcedTransferController": ForcedTransferControllerJson as unknown as Abi,
  "FreezeManager": FreezeManagerJson as unknown as Abi,
  "FundingManager": FundingManagerJson as unknown as Abi,
  "HarvestOracle": HarvestOracleJson as unknown as Abi,
  "IdentityAttestation": IdentityAttestationJson as unknown as Abi,
  "InsurancePool": InsurancePoolJson as unknown as Abi,
  "MarketplaceModule": MarketplaceModuleJson as unknown as Abi,
  "OracleBaseEIP712": OracleBaseEIP712Json as unknown as Abi,
  "PackedUint": PackedUintJson as unknown as Abi,
  "ReentrancyGuard": ReentrancyGuardJson as unknown as Abi,
  "RoleManager": RoleManagerJson as unknown as Abi,
  "SafeERC20": SafeERC20Json as unknown as Abi,
  "SalesProceedsOracle": SalesProceedsOracleJson as unknown as Abi,
  "SettlementQueue": SettlementQueueJson as unknown as Abi,
  "SnapshotModule": SnapshotModuleJson as unknown as Abi,
  "TraceabilityRegistry": TraceabilityRegistryJson as unknown as Abi,
  "TwoStepAdmin": TwoStepAdminJson as unknown as Abi,
  "UAgriErrors": UAgriErrorsJson as unknown as Abi,
  "YieldAccumulator": YieldAccumulatorJson as unknown as Abi,
  "IAggregatorV3": IAggregatorV3Json as unknown as Abi,
  "IAgriBridgeV1": IAgriBridgeV1Json as unknown as Abi,
  "IAgriCampaignRegistryV1": IAgriCampaignRegistryV1Json as unknown as Abi,
  "IAgriComplianceV1": IAgriComplianceV1Json as unknown as Abi,
  "IAgriCustodyV1": IAgriCustodyV1Json as unknown as Abi,
  "IAgriDeliveryV1": IAgriDeliveryV1Json as unknown as Abi,
  "IAgriDisasterAdminV1": IAgriDisasterAdminV1Json as unknown as Abi,
  "IAgriDisasterV1": IAgriDisasterV1Json as unknown as Abi,
  "IAgriDistributionHooksV1": IAgriDistributionHooksV1Json as unknown as Abi,
  "IAgriDistributionV1": IAgriDistributionV1Json as unknown as Abi,
  "IAgriDocumentRegistryV1": IAgriDocumentRegistryV1Json as unknown as Abi,
  "IAgriForcedTransferV1": IAgriForcedTransferV1Json as unknown as Abi,
  "IAgriFreezeV1": IAgriFreezeV1Json as unknown as Abi,
  "IAgriIdentityAttestationV1": IAgriIdentityAttestationV1Json as unknown as Abi,
  "IAgriInsuranceV1": IAgriInsuranceV1Json as unknown as Abi,
  "IAgriMarketplaceV1": IAgriMarketplaceV1Json as unknown as Abi,
  "IAgriModulesV1": IAgriModulesV1Json as unknown as Abi,
  "IAgriOracleBaseV1": IAgriOracleBaseV1Json as unknown as Abi,
  "IAgriOracleSubmitV1": IAgriOracleSubmitV1Json as unknown as Abi,
  "IAgriShareOps": IAgriShareOpsJson as unknown as Abi,
  "IAgriShareTokenSnapshotViews": IAgriShareTokenSnapshotViewsJson as unknown as Abi,
  "IAgriTraceV1": IAgriTraceV1Json as unknown as Abi,
  "IAgriTreasuryV1": IAgriTreasuryV1Json as unknown as Abi,
  "IERC1271__IdentityAttestation": IERC1271_IdentityAttestationJson as unknown as Abi,
  "IERC1271__OracleBaseEIP712": IERC1271_OracleBaseEIP712Json as unknown as Abi,
  "IERC1271__YieldAccumulator": IERC1271_YieldAccumulatorJson as unknown as Abi,
  "IFundingManagerQueueV1": IFundingManagerQueueV1Json as unknown as Abi,
  "ISettlementQueueV1": ISettlementQueueV1Json as unknown as Abi,
  "IShareTokenViews": IShareTokenViewsJson as unknown as Abi,
  "ISnapshotModuleLike": ISnapshotModuleLikeJson as unknown as Abi,
  "IERC1271": IERC1271Json as unknown as Abi,
  "IERC165": IERC165Json as unknown as Abi,
  "IERC20": IERC20Json as unknown as Abi,
  "IERC20Decimals": IERC20DecimalsJson as unknown as Abi,
  "IERC7943Fungible": IERC7943FungibleJson as unknown as Abi,
};

export type AbiManifestEntry = {
  name: string;
  category: string;
  sourceFolder: string;
  artifactPath: string;
  originalName: string;
};

export const abiManifest = abiManifestJson as AbiManifestEntry[];

export function getAbi(name: string): Abi {
  const abi = abiByName[name];
  if (!abi) throw new Error(`ABI not found: ${name}`);
  return abi;
}
